#!/usr/bin/env python3
"""Generates core/src/dmc/DmcTableData.cpp from the source CSV.

Source data: adrianj/CrossStitchCreator, as redistributed and corrected by
the sharlagelfand/dmc R package (data-raw/floss_adrianj.csv + data-raw/floss.R).
The correction tables below are transcribed from that package's cleaning
script so our RGB values match the vetted "floss" dataset it produces.

Run once; the generated .cpp is committed to the repo (no build-time
dependency on this script or the CSV).
"""
import csv
import re
import sys

SRC_CSV = sys.argv[1] if len(sys.argv) > 1 else "floss_adrianj.csv"
OUT_CPP = sys.argv[2] if len(sys.argv) > 2 else "../../core/src/dmc/DmcTableData.cpp"

# Hex codes mangled by Excel in the raw CSV (rgb_code column only; RGB columns
# in the CSV are already correct for these).
HEX_TYPO_FIXES = {
    "221": "883E43",
    "910": "187E56",
    "699": "056517",
    "869": "835E39",
    "310": "000000",
    "434": "985E33",
}

# Entries where RGB and hex disagreed; corrected hex is authoritative and RGB
# is re-derived from it.
RGB_MISMATCH_FIXES = {
    "309": "BA4A4A",
    "3609": "F4AED5",
    "225": "FFDFD5",
    "210": "C39FC3",
    "3755": "93B4CE",
    "3849": "52B3AE",
    "3848": "419392",
    "890": "174923",
    "3830": "B95544",
}

# Order matches sharlagelfand/dmc's data-raw/floss.R clean_floss_name():
# longer tokens first so e.g. "Vy" doesn't get caught mid-substitution, then
# the single-letter tokens (safe because \b anchors them to whole words).
ABBREV = [
    (r"\bUlt\b", "Ultra"),
    (r"\bVy\b", "Very"),
    (r"\bDk\b", "Dark"),
    (r"\bMed\b", "Medium"),
    (r"\bLt\b", "Light"),
    (r"\bVry\b", "Very"),
    (r"\bMd\b", "Medium"),
    (r"\bM\b", "Medium"),
    (r"\bV\b", "Very"),
    (r"\bD\b", "Dark"),
    (r"\bVD\b", "Very Dark"),
    (r"\bVyDk\b", "Very Dark"),
    (r"\bGrn\b", "Green"),
    (r"\bBrn\b", "Brown"),
    (r"\bU\b", "Ultra"),
]


def clean_name(name: str) -> str:
    name = name.strip()
    name = re.sub(r"\s+", " ", name)
    for pattern, repl in ABBREV:
        name = re.sub(pattern, repl, name)
    return name


def hex_to_rgb(h: str):
    h = h.strip().lstrip("#")
    return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)


def cpp_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    rows = []
    with open(SRC_CSV, newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        for row in reader:
            code = row["Floss#"].strip()
            name = clean_name(row["Description"])
            r, g, b = int(row["Red"]), int(row["Green"]), int(row["Blue"])

            if code in RGB_MISMATCH_FIXES:
                r, g, b = hex_to_rgb(RGB_MISMATCH_FIXES[code])
            # HEX_TYPO_FIXES only affects the display hex string, not R/G/B,
            # and we don't store a separate hex field (derived at runtime).

            rows.append((code, name, r, g, b))

    rows.sort(key=lambda t: (len(t[0]), t[0]))

    seen = set()
    dupes = [r[0] for r in rows if r[0] in seen or seen.add(r[0])]
    if dupes:
        print(f"WARNING: duplicate DMC codes in source data: {dupes}", file=sys.stderr)

    with open(OUT_CPP, "w", encoding="utf-8") as out:
        out.write("// Generated by tools/dmc_gen/generate_dmc_table.py. Do not edit by hand.\n")
        out.write("// Source: adrianj/CrossStitchCreator via sharlagelfand/dmc (R package),\n")
        out.write("// with the same typo/mismatch corrections applied.\n\n")
        out.write('#include "ss/core/dmc/DmcTable.h"\n\n')
        out.write("namespace ss::core::dmc {\n\n")
        out.write(f"const DmcColor kDmcTableData[{len(rows)}] = {{\n")
        for code, name, r, g, b in rows:
            out.write(
                f'    {{"{cpp_escape(code)}", "{cpp_escape(name)}", '
                f'{r}, {g}, {b}}},\n'
            )
        out.write("};\n\n")
        out.write(f"const int kDmcTableSize = {len(rows)};\n\n")
        out.write("} // namespace ss::core::dmc\n")

    print(f"Wrote {len(rows)} DMC colors to {OUT_CPP}")


if __name__ == "__main__":
    main()
